#include "hal_data.h"
#include <stdio.h>

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER
/* Callback function */

//
void delay(int ms){
    R_BSP_SoftwareDelay(ms, BSP_DELAY_UNITS_MILLISECONDS);
}
//SPI전송 완료 등의 이벤트를 처리하기 위한 콜백 함수부분
void spi_callback(spi_callback_args_t *p_args)
{
    /* TODO: add your own code here */
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    //i2c장치 초기화(모터햇의 주소)
    init(0x6f);
    //PWM(0x6f);
    //PWM주파수 설정
    setPWMFreq(60);
    //모터 중립위치
    Mid();
    delay(10);

    //모터 속도 설정
    int speed = 150;
    setSpeed(150);

    uint8_t data = 0x0F;
    uint8_t readData = 0x00;
    while(1){
        //SPI통신을 통해 얻은 데이터 readData를 수신
        R_SPI_WriteRead(&g_spi1_ctrl, &data, &readData, 1, SPI_BIT_WIDTH_8_BITS);
        if( readData == 'w'){
            Forward();
        }
        if( readData == 'x'){
            Backward();
        }
        if( readData == 'f'){
            Release();
        }
        if( readData == 's'){
            Mid();
        }
        if( readData == 'a'){
            Left();
        }
        if( readData == 'd'){
            Right();
        }
        delay(10);
    }
}


/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {

    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
        R_IIC_MASTER_Open(&g_i2c_master0_ctrl, &g_i2c_master0_cfg);
        R_SPI_Open(&g_spi1_ctrl, &g_spi1_cfg);
    }
}
